### ISSUE TITLE
org.springframework.core.convert.ConverterNotFoundException when using Hotswap agent

### ISSUE THREAD

**Issue by jorgheymans** [HotswapProjects/HotswapAgent#639]
Hi,

I have a small spring-boot + Vaadin application that starts fine without hotswapagent. When enabling hotswapagent though (either using the IntelliJ vaadin plugin or by manually copying hotswap-agent.jar to the jdk directory), i get this error during startup:

```
Failed to bind properties under 'my.property.allowed-media-types[0]' to org.apache.tika.mime.MediaType:

    Property: my.property.upload.allowed-media-types[0]
    Value: "text/plain"
    Origin: class path resource [application.yml] - 48:11
    Reason: org.springframework.core.convert.ConverterNotFoundException: No converter found capable of converting from type [java.lang.String] to type [org.apache.tika.mime.MediaType]

Action:

Update your application's configuration

```

Any idea what could be causing this ? Using `OpenJDK Runtime Environment JBR-17.0.14+1-1367.22-jcef (build 17.0.14+1-b1367.22)`, hotswap-agent 2.0.2.

**Comment by jorgheymans** [comment]
The offending yaml is a bit of custom config in `application.yml` :

```yaml
    upload:
      allowed-media-types:
#        - text/plain
#        - application/msword
#        - application/vnd.openxmlformats-officedocument.wordprocessingml.document
#        - image/jpeg
#        - application/vnd.ms-outlook
#        - application/pdf
#        - application/vnd.ms-excel
#        - application/vnd.openxmlformats-officedocument.spreadsheetml.sheet
```

If i uncomment one of the media-types the error occurs. When all are commented out, the application starts fine with the hotswap agent (either through the Vaadin plugin or with jdk/lib/hotswap/hotswap-agent.jar).
